/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iproxy.client.gui;

import com.iproxys.connectivity.ServerComunication;
import com.iproxys.interfaces.UserManageBeanRemote;
import iproxy.client.Beans.User;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Edgar Omar
 */
public class manejoUsuario extends javax.swing.JDialog {

    /**
     * Creates new form manejoUsuario
     */
    private DefaultListModel userUnblockModel;
    private crearUsuario crear_user;
    public static User newUser = null;

    public manejoUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        userUnblockModel = new DefaultListModel();
        ServerComunication instance = ServerComunication.getInstance();
        if (instance != null) {
            UserManageBeanRemote UserManageBean = instance.UserManageBean();
            if (UserManageBean != null) {
                List<User> allIP = UserManageBean.getAllUsers();
                
                for (User users : allIP) {
                    
                    userUnblockModel.addElement(users.getUsername());
                }
            } else {
                ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

            }
        } else {
            ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

        }
initComponents();

userList.setSelectionMode(
                ListSelectionModel.SINGLE_SELECTION);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        atrasButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList(userUnblockModel);
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addUser = new javax.swing.JButton();
        delUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(null);

        atrasButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iproxy/client/gui/images/back.png"))); // NOI18N
        atrasButton.setContentAreaFilled(false);
        atrasButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        atrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasButtonActionPerformed(evt);
            }
        });
        jPanel1.add(atrasButton);
        atrasButton.setBounds(10, 250, 40, 40);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("MANEJO DE USUARIOs");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 300, 30);

        userList.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane1.setViewportView(userList);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 280, 150);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel3.setText("AGREGAR");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 290, 70, 15);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel4.setText("ELIMINAR");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(230, 290, 70, 15);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        jLabel5.setText("ATRÁS");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 290, 50, 15);

        addUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iproxy/client/gui/images/add_user.jpg"))); // NOI18N
        addUser.setContentAreaFilled(false);
        addUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jPanel1.add(addUser);
        addUser.setBounds(120, 250, 50, 40);

        delUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iproxy/client/gui/images/Agt_icon.png"))); // NOI18N
        delUser.setContentAreaFilled(false);
        delUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delUserActionPerformed(evt);
            }
        });
        jPanel1.add(delUser);
        delUser.setBounds(230, 250, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasButtonActionPerformed
        // TODO add your handling code here:
        //  mainFrame.user.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_atrasButtonActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        // TODO add your handling code here:
        crear_user = new crearUsuario(null, rootPaneCheckingEnabled);
        crear_user.setLocationRelativeTo(this);
        crear_user.setVisible(true);
        if (newUser != null) {
            this.setEnabled(false);
            ServerComunication instance = ServerComunication.getInstance();

            if (instance != null) {
                UserManageBeanRemote UserManageBean = instance.UserManageBean();
                if (UserManageBean != null) {

                    if (UserManageBean.Insert(newUser)) {
                        ShowMessages.ShowSucessMessage("Se ha agregado el Usuario con exito", "Iproxys : Mensaje de Notificacion", this);
                        userUnblockModel.removeAllElements();
                        List<User> allUsers = UserManageBean.getAllUsers();
                        for (User Usernew : allUsers) {
                            userUnblockModel.addElement(Usernew.getUsername());
                        }
                    } else {
                        ShowMessages.ShowErrorMessage("No se Pudo agregar el Usuario, Verifique que no se encuentre en la lista", "Iproxys : Mensaje de Notificacion", this);

                    }

                } else {
                    ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

                }
            } else {
                ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

            }
            this.setEnabled(true);
        }
        newUser = null;
    }//GEN-LAST:event_addUserActionPerformed

    private void delUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delUserActionPerformed
        // TODO add your handling code here:
        int selectedIndex = userList.getSelectedIndex();

        if (selectedIndex == -1) {
            ShowMessages.ShowErrorMessage("Se Debe Elegir un Usuario", "Iproxys Error: Imposible Continuar", this);
        } else {
            ServerComunication instance = ServerComunication.getInstance();
            this.setEnabled(false);

            if (instance != null) {
                UserManageBeanRemote UserManageBean = instance.UserManageBean();
                if (UserManageBean != null) {
                    if (UserManageBean.remove((String) userUnblockModel.get(userList.getSelectedIndex()))) {
                        ShowMessages.ShowSucessMessage("Se ha eliminado la ip con exito", "Iproxys : Mensaje de Notificacion", this);
                        userUnblockModel.removeAllElements();
                        List<User> allUsers = UserManageBean.getAllUsers();
                        for (User Usernew : allUsers) {
                            userUnblockModel.addElement(Usernew.getUsername());
                        }
                    } else {
                        ShowMessages.ShowErrorMessage("No se Pudo eliminar la ip", "Iproxys : Mensaje de Notificacion", this);
                    }
                } else {
                    ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

                }
            } else {

                ShowMessages.ShowErrorMessage("No se Pudo Contactar el servidor", "Iproxys : Mensaje de Notificacion", this);

            }
            this.setEnabled(true);

        }
    }//GEN-LAST:event_delUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manejoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                manejoUsuario dialog = new manejoUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JButton atrasButton;
    private javax.swing.JButton delUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList userList;
    // End of variables declaration//GEN-END:variables
}
